#!/usr/bin/env ruby

boot_disk_file="dist/disk"
storage_disk_file="dist/storage"

disks = []

Dir["dist/{disk,storage*}"].each_with_index do |file, index|
  disks << "-drive file=#{file},if=ide,index=#{index},media=disk"
end

qemu_command = "qemu -m 384m #{disks.join(' ')} -soundhw es1370 -net nic,vlan=0 -net tap,ifname=tap0,script=config/qemu-ifup,downscript=config/qemu-ifdown"
puts "Run #{qemu_command}"
system qemu_command
