#!/bin/sh -e

if [ $# == 0 ]; then
    echo "Usage: `basename $0` <target>"
    exit 1
fi

target=$1

echo "Modify /boot/current.yml in $target"
ssh $target "mount -o remount,rw /boot && sed -i '/name/ s/2010[0-9]*/20100101/' /boot/current.yml && mount -o remount,ro /boot"
echo "Remove cached Releases in $target"
ssh $target "cd /usr/share/pige && sudo -u www-data ./script/runner --environment=production 'Release.destroy_all'"
echo "Done. Please visit http://$target/releases"
