#!/bin/bash

daemon="pige-job"
pid_file="/var/run/pige.pid"

function check_daemon() {
  if [ ! -f $pid_file ]; then
      return 1
  fi

  pid=`cat $pid_file`
  if [ -z "$pid" ]; then
      return 1
  fi

  cmdline_file="/proc/$pid/cmdline"
  if [ ! -f "$cmdline_file" ]; then
      return 1
  fi

  if ! grep -q $daemon $cmdline_file; then
      return 1
  fi

  return 0
}

if ! check_daemon; then
    echo "No daemon found, restart it" | logger -i -t "check-delayed-jobs" 
    /etc/init.d/pigecontrol restart
fi
